// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystqgujyvdmgoltpwkzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdHFndWp5dmRtZ29sdHB3a3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzUxNzIsImV4cCI6MjA2NzkxMTE3Mn0.Afafnz4nospYj3aNt0_fvUu5iySt3sUbXdD7CheLs7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});